version: "3.7"

services:
  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: bold9
      MYSQL_ROOT_PASSWORD: root

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: server
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - mysql
    environment:
      DB_HOST: db
      DB_PORT: 3306
    env_file:
      - .env

volumes:
  server:
  mysql:
